# Generated by Django 4.2.13 on 2024-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
